adjective1 = input("Please enter an adjective ")
noun1 = input("Please enter a noun: ")
adjectiv2 = input("Please enter an adjective ")
verb1 = input("Please enter a verb")
adjective3 = input("Please enter an adjective ")

print(f"Today I went to a {adjective1} Zoo")
print(f"In an exhibit i saw {noun1}")
print(f"{noun1} was {adjectiv2} and {adjective1}")
print(f"I was {adjective3}")